### PR TITLE
Include bin hash in cache key

### PR DESCRIPTION
**Pull request by bhperry**
Add sha256 hash of the micromamba binary to the cache key so broken environments created from previous versions won't be restored for a new version.

Closes https://github.com/mamba-org/setup-micromamba/issues/91

### CODE REVIEW

File: src/cache.ts [hunk 1]
```diff
@@ -40,7 +40,11 @@ const generateEnvironmentKey = (options: Options, prefix: string) => {
   const envName = options.environmentName ? `-${options.environmentName}` : ''
   const createArgs = options.createArgs ? `-args-${sha256Short(JSON.stringify(options.createArgs))}` : ''
   const rootPrefix = `-root-${sha256Short(options.micromambaRootPath)}`
-  const key = `${prefix}${arch}${envName}${createArgs}${rootPrefix}`
+  const binHash = fs.readBinaryFile(options.micromambaBinPath).then((content) => {
+    return sha256(content)
+  })
```
Comment (pavelzw) [inline src/cache.ts:45]:
```suggestion
  const binHash = fs.readBinaryFile(options.micromambaBinPath).then(sha256)
```

**Comment by pavelzw** [comment]
Could you also compile the action and bump its version in package.json?

**Comment by bhperry** [comment]
> Could you also compile the action and bump its version in package.json?

@pavelzw minor bump for this?

**Comment by pavelzw** [comment]
Sure 👍🏻

**Comment by bhperry** [comment]
Is `test.sh` outdated? Tried to run it, but no `index.js` in dist

**Comment by pavelzw** [comment]
Yes seems like it 🤔 I nowadays just run the tests from GitHub ci

**Comment by pavelzw** [comment]
```

Error: src/cache.ts(43,22): error TS2339: Property 'readBinaryFile' does not exist on type 'typeof import("fs/promises")'.

```

**Comment by bhperry** [comment]
hmm looked that one up somewhere, guess I was looking at the wrong fs package

**Comment by bhperry** [comment]
seems like regular readFile with no encoding should do the trick

**Comment by pavelzw** [comment]
The ci failures look unrelated. I'll take a look at them later

**Comment by pavelzw** [comment]
the remaining failing ci is tracked in #230

**Comment by tsibley** [comment]
FWIW, this doesn't work as expected because a promise is interpolated into the cache key string rather than the value the promise resolves to, e.g. I see cache keys like:

    2025-09-16-linux-64-augur-args-30d39f4-root-dcc80ee-bin-[object Promise]

The issue is this bit of code added by 59b1132

https://github.com/mamba-org/setup-micromamba/blob/7f29b8b80078b1b601dfa018b0f7425c587c63bb/src/cache.ts#L43-L45

because `binHash` is a promise.

**Comment by bhperry** [comment]
https://github.com/mamba-org/setup-micromamba/pull/284
